# Secrets
SECRET_KEY_BASE: "a8eeb7178163cf8f62823194951ddc3a127bc055de6e82d7184f9fef59dfb6c158c5275a3ef36c342263bf8b5d11763deb00a978f10783c1b803a5728f98fae5"
PAPERCLIP_HASH_SECRET: "AdzqOvC1qHP2YE9FV4fIb/cKRxTUwubm7NhXOCvdN9uw2Mzqu0OPU5LDweLC/x0chwqUBDPyt6V4PC+nCaR9jA2TIKdq9lZp+SlXPuIGKcUtqEQF+W2MeUeeDMMlV1hMfzkD75VdzNQIOhoaDpLXqWte/8smxa94vDtUuwDE8rg="

# File storage For local file storage
PAPERCLIP_STORAGE: "filesystem"

# For S3 file storage 
#PAPERCLIP_STORAGE: "s3" 
#AWS_ACCESS_KEY_ID: "" 
#AWS_REGION: "" 
#AWS_SECRET_ACCESS_KEY: "" 
#S3_BUCKET: "" 
#S3_HOST_NAME: ""

# Mailer settings
MAIL_FROM: "SciNote Assistant <admin@scinotepmtresearch.org>" 
MAIL_REPLYTO: "SciNote Assistant <admin@scinotepmtresearch.org>" 
SMTP_ADDRESS: "smtp.office365.com" 
SMTP_PORT: "587" 
SMTP_DOMAIN: "hjsfmail.org" 
SMTP_USERNAME: "admin@hjsfmail.org" 
SMTP_PASSWORD: "Goddamnit83!" 
SMTP_AUTH_METHOD: "plain" 
MAIL_SERVER_URL: "scinote.pmtresearch.org"

# Sign-up process
NEW_TEAM_ON_SIGNUP: "true" 
ENABLE_EMAIL_CONFIRMATIONS: "false"
ENABLE_USER_REGISTRATION: "true"

# Initial admin user
ADMIN_NAME: "Admin"
ADMIN_EMAIL: "admin@scinote.pmtresearch.org"
ADMIN_PASSWORD: "inHisHouseAtRlyehDeadCthulhuWaitsDreaming"


# LinkedIn sign-in
LINKEDIN_SIGNIN_ENABLED: "true"
LINKEDIN_KEY: "8684xbvj3qkdi4"
LINKEDIN_SECRET: "eOFRGwdIeDsHNJBx"

# additional configurations
ENABLE_RECAPTCHA: "false"
ENABLE_USER_CONFIRMATION: "false"
ENABLE_USER_REGISTRATION: "true"
DEFACE_ENABLED: "false"
